nombre = input("Dame tu nombre: ")
edad  = input("Dame tu edad: ")
direccion = input("Dame tu direccion: ")
telefono = input("Dame tu telefono: ")
print (nombre + "" + edad + "" + direccion + "" + telefono)